### PR TITLE
FEAT(#003): FIRST FOOTER VERSION

### LINKED ISSUE #3: Diseño de footer

### PR DESCRIPTION
**Pull request by TomasCB24**
I have completed the graphical implementation of the app footer. The footer contains a series of useful elements for the user

There is a bug inherited from the 'develop' branch about the overflow of the landing page, which causes a horizontal scroll.

The footer has been implemented for now on the landing page, waiting to be added to the other pages if required.

Most of the links are empty, waiting to create these pages and components

**For the reviewer**

Check if it complies with the established:

- [ ] Verify that the overall layout of the footer component is visually appealing and user-friendly.
- [ ] Check the responsiveness of the page on various devices and screen sizes.
- [ ] Ensure email and slack links works correctly.
- [ ] Review the code for readability, maintainability, and adherence to coding standards.

### CODE REVIEW

**Review by Alex-GF — COMMENTED** [review]
I have made some comments in the meeting we had today to @migromarj. Once they're all studied, I'll gladly approve the request

**Comment by mrarjona** [comment]
> I have made some comments in the meeting we had today to @migromarj. Once they're all studied, I'll gladly approve the request

@Alex-GF, I have taken into account everything we talked about, take a look at it if you can and let me know what you think.

**Review by Alex-GF — DISMISSED** [review]
I have sent some optional comments to @migromarj, evaluate them and merge whenever you want.

**Review by Alex-GF — APPROVED** [review]
Great Job!!

**Pull request merged**
